/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Subjects */
        get: operations["read_subjects_api_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_api_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Subject */
        get: operations["read_subject_api_subjects__subject_id__get"];
        put?: never;
        post?: never;
        /** Delete Subject */
        delete: operations["delete_subject_api_subjects__subject_id__delete"];
        options?: never;
        head?: never;
        /** Update Subject */
        patch: operations["update_subject_api_subjects__subject_id__patch"];
        trace?: never;
    };
    "/api/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Decks */
        get: operations["read_decks_api_decks_get"];
        put?: never;
        /** Create Deck */
        post: operations["create_deck_api_decks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/{deck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Deck */
        get: operations["read_deck_api_decks__deck_id__get"];
        put?: never;
        post?: never;
        /** Delete Deck */
        delete: operations["delete_deck_api_decks__deck_id__delete"];
        options?: never;
        head?: never;
        /** Update Deck */
        patch: operations["update_deck_api_decks__deck_id__patch"];
        trace?: never;
    };
    "/api/decks/{deck_id}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Field Defs */
        get: operations["read_field_defs_api_decks__deck_id__fields_get"];
        put?: never;
        /** Create Field Def */
        post: operations["create_field_def_api_decks__deck_id__fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/{deck_id}/fields/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Field Defs */
        post: operations["reorder_field_defs_api_decks__deck_id__fields_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Field Def */
        get: operations["read_field_def_api_fields__field_id__get"];
        put?: never;
        post?: never;
        /** Archive Field Def */
        delete: operations["archive_field_def_api_fields__field_id__delete"];
        options?: never;
        head?: never;
        /** Update Field Def */
        patch: operations["update_field_def_api_fields__field_id__patch"];
        trace?: never;
    };
    "/api/fields/{field_id}/hard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hard Delete Field Def */
        delete: operations["hard_delete_field_def_api_fields__field_id__hard_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Cards */
        get: operations["read_cards_api_cards_get"];
        put?: never;
        /** Create Card */
        post: operations["create_card_api_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Card */
        get: operations["read_card_api_cards__card_id__get"];
        put?: never;
        post?: never;
        /** Delete Card */
        delete: operations["delete_card_api_cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card */
        patch: operations["update_card_api_cards__card_id__patch"];
        trace?: never;
    };
    "/api/cards/{card_id}/mastery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Card Mastery */
        get: operations["read_card_mastery_api_cards__card_id__mastery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck_practice_configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Deck Practice Configs */
        get: operations["read_deck_practice_configs_api_deck_practice_configs_get"];
        put?: never;
        /** Create Deck Practice Config */
        post: operations["create_deck_practice_config_api_deck_practice_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck_practice_configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Deck Practice Config */
        get: operations["read_deck_practice_config_api_deck_practice_configs__config_id__get"];
        put?: never;
        post?: never;
        /** Delete Deck Practice Config */
        delete: operations["delete_deck_practice_config_api_deck_practice_configs__config_id__delete"];
        options?: never;
        head?: never;
        /** Update Deck Practice Config */
        patch: operations["update_deck_practice_config_api_deck_practice_configs__config_id__patch"];
        trace?: never;
    };
    "/api/practice_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Practice Session */
        post: operations["create_practice_session_api_practice_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice_sessions/{practice_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Practice Session */
        get: operations["read_practice_session_api_practice_sessions__practice_session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice_sessions/{practice_session_id}/current_card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current Practice Card */
        get: operations["read_current_practice_card_api_practice_sessions__practice_session_id__current_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice_cards/{practice_card_id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate Practice Card */
        post: operations["rate_practice_card_api_practice_cards__practice_card_id__rate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CardBatchCreate
         * @description `values` is keyed by a real field_def id or a same-request `client_key`
         *     (§2.3, widened in Phase 7 — see `CardBatchUpdate`).
         */
        CardBatchCreate: {
            /** Values */
            values?: {
                [key: string]: string | null;
            };
        };
        /** CardBatchOps */
        CardBatchOps: {
            /** Create */
            create?: components["schemas"]["CardBatchCreate"][];
            /** Update */
            update?: components["schemas"]["CardBatchUpdate"][];
            /** Delete */
            delete?: string[];
        };
        /**
         * CardBatchUpdate
         * @description `values` is partial (only changed fields), keyed by a real field_def id or a
         *     same-request `client_key` — the deck editor's edit-mode diff (Phase 7) can set an
         *     existing card's value for a field created in the very same request (field
         *     creates are always applied before card updates, per the stated operation order,
         *     so the field already has a real row by the time this runs).
         */
        CardBatchUpdate: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Values */
            values?: {
                [key: string]: string | null;
            };
        };
        /** CardCreate */
        CardCreate: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * CardMasteryRead
         * @description Display-only aggregate — never stored, computed fresh from card_field_mastery
         *     via the active MasteryStrategy on every request (invariant 8).
         */
        CardMasteryRead: {
            /** Mastery */
            mastery: number;
            /** Reviewed Field Count */
            reviewed_field_count: number;
        };
        /** CardRead */
        CardRead: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** CardUpdate */
        CardUpdate: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * DeckBatchEdit
         * @description `PATCH /api/decks/{id}` body (§2.3, Phase 6). Every top-level key is optional —
         *     a request can touch just `name`, just `field_defs`, or any combination — but the
         *     whole thing is applied as one transaction: a failure anywhere rolls back
         *     everything, including an already-changed `name`.
         */
        DeckBatchEdit: {
            /** Name */
            name?: string | null;
            /** Subject Id */
            subject_id?: string | null;
            field_defs?: components["schemas"]["FieldDefBatchOps"] | null;
            cards?: components["schemas"]["CardBatchOps"] | null;
        };
        /**
         * DeckCardCreate
         * @description One card in an atomic deck-create payload: `values[i]` belongs to
         *     `field_defs[i]` by position (D6) — no client-side field ids yet to key by.
         */
        DeckCardCreate: {
            /** Values */
            values: (string | null)[];
        };
        /** DeckCreate */
        DeckCreate: {
            /** Name */
            name: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Field Defs */
            field_defs: components["schemas"]["FieldDefCreate"][];
            /** Cards */
            cards: components["schemas"]["DeckCardCreate"][];
        };
        /** DeckDetail */
        DeckDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Field Defs */
            field_defs: components["schemas"]["DeckFieldDefRead"][];
            /** Cards */
            cards: components["schemas"]["CardRead"][];
        };
        /** DeckFieldDefRead */
        DeckFieldDefRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            type: components["schemas"]["FieldType"];
            /** Position */
            position: number;
        };
        /** DeckPracticeConfigCreate */
        DeckPracticeConfigCreate: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Name */
            name: string;
            /** Prompt Field Ids */
            prompt_field_ids: string[];
            /** Answer Field Ids */
            answer_field_ids: string[];
            /** Prompt Pool Ids */
            prompt_pool_ids: string[];
            /** Prompt Pool Counts */
            prompt_pool_counts: number[];
            /** Answer Pool Ids */
            answer_pool_ids: string[];
            /** Answer Pool Counts */
            answer_pool_counts: number[];
        };
        /** DeckPracticeConfigRead */
        DeckPracticeConfigRead: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Name */
            name: string;
            /** Prompt Field Ids */
            prompt_field_ids: string[];
            /** Answer Field Ids */
            answer_field_ids: string[];
            /** Prompt Pool Ids */
            prompt_pool_ids: string[];
            /** Prompt Pool Counts */
            prompt_pool_counts: number[];
            /** Answer Pool Ids */
            answer_pool_ids: string[];
            /** Answer Pool Counts */
            answer_pool_counts: number[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DeckPracticeConfigUpdate */
        DeckPracticeConfigUpdate: {
            /** Name */
            name?: string | null;
            /** Prompt Field Ids */
            prompt_field_ids?: string[] | null;
            /** Answer Field Ids */
            answer_field_ids?: string[] | null;
            /** Prompt Pool Ids */
            prompt_pool_ids?: string[] | null;
            /** Prompt Pool Counts */
            prompt_pool_counts?: number[] | null;
            /** Answer Pool Ids */
            answer_pool_ids?: string[] | null;
            /** Answer Pool Counts */
            answer_pool_counts?: number[] | null;
        };
        /**
         * DeckSummary
         * @description DeckRead plus preview data for a list row (Phase 2.6) — card_count and
         *     field_names (position order, active fields only). Only `GET /api/decks` returns
         *     this; the single-deck reads (`GET`/`POST`/`PATCH /api/decks/{id}`) return the
         *     richer `DeckDetail` instead, which already includes everything here except these
         *     two list-row-only fields.
         */
        DeckSummary: {
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Name */
            name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Card Count */
            card_count: number;
            /** Field Names */
            field_names: string[];
        };
        /** FieldDefBatchCreate */
        FieldDefBatchCreate: {
            /** Client Key */
            client_key: string;
            /** Name */
            name: string;
            type: components["schemas"]["FieldType"];
        };
        /**
         * FieldDefBatchOps
         * @description §2.3's `field_defs` changeset. Applied in the stated order (create → update →
         *     delete → reorder) inside the batch-edit transaction — this model just carries the
         *     four lists; the service resolves ids/client_keys and enforces D3.
         */
        FieldDefBatchOps: {
            /** Create */
            create?: components["schemas"]["FieldDefBatchCreate"][];
            /** Update */
            update?: components["schemas"]["FieldDefBatchUpdate"][];
            /** Delete */
            delete?: string[];
            /** Order */
            order?: string[];
        };
        /** FieldDefBatchUpdate */
        FieldDefBatchUpdate: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            type?: components["schemas"]["FieldType"] | null;
        };
        /** FieldDefCreate */
        FieldDefCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["FieldType"];
        };
        /** FieldDefRead */
        FieldDefRead: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Name */
            name: string;
            type: components["schemas"]["FieldType"];
            /** Position */
            position: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FieldDefUpdate */
        FieldDefUpdate: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["FieldType"] | null;
        };
        /**
         * FieldType
         * @enum {string}
         */
        FieldType: "text" | "image" | "audio";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PracticeCardRead */
        PracticeCardRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Practice Session Id
             * Format: uuid
             */
            practice_session_id: string;
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** Position */
            position: number;
            /** Prompts */
            prompts: string[];
            /** Answers */
            answers: string[];
            status: components["schemas"]["PracticeCardStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PracticeCardStatus
         * @enum {string}
         */
        PracticeCardStatus: "pending" | "passed" | "failed";
        /** PracticeSessionCreate */
        PracticeSessionCreate: {
            /** Deck Practice Config Ids */
            deck_practice_config_ids: string[];
        };
        /** PracticeSessionRead */
        PracticeSessionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RatingSubmission */
        RatingSubmission: {
            /** Ratings */
            ratings: {
                [key: string]: number;
            };
        };
        /** RatingSubmissionResult */
        RatingSubmissionResult: {
            rated_practice_card: components["schemas"]["PracticeCardRead"];
            requeued_practice_card: components["schemas"]["PracticeCardRead"] | null;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "active" | "completed" | "abandoned";
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
            /**
             * Icon
             * @default book-open
             */
            icon?: string;
            /**
             * Description
             * @default
             */
            description?: string;
        };
        /** SubjectRead */
        SubjectRead: {
            /** Name */
            name: string;
            /**
             * Icon
             * @default book-open
             */
            icon?: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
        };
        /**
         * SubjectSummary
         * @description SubjectRead plus a deck count for a library list row (Phase 2.6). Only
         *     `GET /api/subjects` returns this — the subject detail page derives its own deck/
         *     card counts from the (separately-fetched, already-enriched) deck list instead of
         *     needing this here too.
         */
        SubjectSummary: {
            /** Name */
            name: string;
            /**
             * Icon
             * @default book-open
             */
            icon?: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Deck Count */
            deck_count: number;
        };
        /** SubjectUpdate */
        SubjectUpdate: {
            /** Name */
            name?: string | null;
            /** Icon */
            icon?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_subjects_api_subjects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_api_subjects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_subject_api_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_api_subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_api_subjects__subject_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_decks_api_decks_get: {
        parameters: {
            query?: {
                subject_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deck_api_decks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_deck_api_decks__deck_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deck_api_decks__deck_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deck_api_decks__deck_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckBatchEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_field_defs_api_decks__deck_id__fields_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_field_def_api_decks__deck_id__fields_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldDefCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_field_defs_api_decks__deck_id__fields_reorder_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_field_def_api_fields__field_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_field_def_api_fields__field_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_field_def_api_fields__field_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldDefUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hard_delete_field_def_api_fields__field_id__hard_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_cards_api_cards_get: {
        parameters: {
            query: {
                deck_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_card_api_cards_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_card_api_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_api_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_api_cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_card_mastery_api_cards__card_id__mastery_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardMasteryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_deck_practice_configs_api_deck_practice_configs_get: {
        parameters: {
            query: {
                deck_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckPracticeConfigRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deck_practice_config_api_deck_practice_configs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckPracticeConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckPracticeConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_deck_practice_config_api_deck_practice_configs__config_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckPracticeConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deck_practice_config_api_deck_practice_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deck_practice_config_api_deck_practice_configs__config_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckPracticeConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckPracticeConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practice_session_api_practice_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_practice_session_api_practice_sessions__practice_session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                practice_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_practice_card_api_practice_sessions__practice_session_id__current_card_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                practice_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeCardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_practice_card_api_practice_cards__practice_card_id__rate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                practice_card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSubmissionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
