/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/subjects/subject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Subject */
        post: operations["create_subject_api_subjects_subject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/subject/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Subject */
        get: operations["read_subject_api_subjects_subject__id__get"];
        put?: never;
        post?: never;
        /** Delete Subject */
        delete: operations["delete_subject_api_subjects_subject__id__delete"];
        options?: never;
        head?: never;
        /** Update Subject */
        patch: operations["update_subject_api_subjects_subject__id__patch"];
        trace?: never;
    };
    "/api/decks/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Deck */
        post: operations["create_deck_api_decks_deck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/deck/{deck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Deck */
        get: operations["read_deck_api_decks_deck__deck_id__get"];
        /** Update Deck */
        put: operations["update_deck_api_decks_deck__deck_id__put"];
        post?: never;
        /** Delete Deck */
        delete: operations["delete_deck_api_decks_deck__deck_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Card */
        post: operations["create_card_api_cards_card_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/card/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Card */
        get: operations["read_card_api_cards_card__card_id__get"];
        /** Update Card */
        put: operations["update_card_api_cards_card__card_id__put"];
        post?: never;
        /** Delete Card */
        delete: operations["delete_card_api_cards_card__card_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck_configs/deck_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Deck Config */
        post: operations["create_deck_config_api_deck_configs_deck_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck_configs/deck_config/{deck_config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Deck Config */
        get: operations["read_deck_config_api_deck_configs_deck_config__deck_config_id__get"];
        put?: never;
        post?: never;
        /** Delete Deck Config */
        delete: operations["delete_deck_config_api_deck_configs_deck_config__deck_config_id__delete"];
        options?: never;
        head?: never;
        /** Update Deck Config */
        patch: operations["update_deck_config_api_deck_configs_deck_config__deck_config_id__patch"];
        trace?: never;
    };
    "/api/practice_sessions/practice_session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Practice Session */
        post: operations["create_practice_session_api_practice_sessions_practice_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice_sessions/practice_session/{practice_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Practice Session */
        get: operations["read_practice_session_api_practice_sessions_practice_session__practice_session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice_sessions/practice_session/{practice_session_id}/practice_card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Practice Card */
        get: operations["read_practice_card_api_practice_sessions_practice_session__practice_session_id__practice_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardCreate */
        CardCreate: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
        };
        /** CardRead */
        CardRead: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Modified
             * Format: date-time
             */
            last_modified: string;
        };
        /** CardUpdate */
        CardUpdate: {
            /** Deck Id */
            deck_id?: string | null;
            /** Fields */
            fields?: {
                [key: string]: unknown;
            } | null;
        };
        /** DeckConfigCreate */
        DeckConfigCreate: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Static Reveals */
            static_reveals: string[];
            /** Static Conceals */
            static_conceals: string[];
            /** Dynamic Reveals */
            dynamic_reveals: string[];
            /** Dynamic Reveal Quantities */
            dynamic_reveal_quantities: number[];
            /** Dynamic Conceals */
            dynamic_conceals: string[];
            /** Dynamic Conceal Quantities */
            dynamic_conceal_quantities: number[];
        };
        /** DeckConfigRead */
        DeckConfigRead: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Static Reveals */
            static_reveals: string[];
            /** Static Conceals */
            static_conceals: string[];
            /** Dynamic Reveals */
            dynamic_reveals: string[];
            /** Dynamic Reveal Quantities */
            dynamic_reveal_quantities: number[];
            /** Dynamic Conceals */
            dynamic_conceals: string[];
            /** Dynamic Conceal Quantities */
            dynamic_conceal_quantities: number[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** DeckConfigUpdate */
        DeckConfigUpdate: {
            /** Deck Id */
            deck_id?: string | null;
            /** Static Reveals */
            static_reveals?: string[] | null;
            /** Static Conceals */
            static_conceals?: string[] | null;
            /** Dynamic Reveals */
            dynamic_reveals?: string[] | null;
            /** Dynamic Reveal Quantities */
            dynamic_reveal_quantities?: number[] | null;
            /** Dynamic Conceals */
            dynamic_conceals?: string[] | null;
            /** Dynamic Conceal Quantities */
            dynamic_conceal_quantities?: number[] | null;
        };
        /** DeckCreate */
        DeckCreate: {
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Name */
            name: string;
            /** Deck Schema */
            deck_schema: {
                [key: string]: string;
            };
        };
        /** DeckRead */
        DeckRead: {
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Name */
            name: string;
            /** Deck Schema */
            deck_schema: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** DeckUpdate */
        DeckUpdate: {
            /** Subject Id */
            subject_id?: string | null;
            /** Name */
            name?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PracticeCardRead */
        PracticeCardRead: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Practice Session Id
             * Format: uuid
             */
            practice_session_id: string;
            /** Position */
            position: number;
            /** Static Reveals */
            static_reveals: {
                [key: string]: unknown;
            };
            /** Static Conceals */
            static_conceals: {
                [key: string]: unknown;
            };
            /** Dynamic Reveals */
            dynamic_reveals: {
                [key: string]: unknown;
            };
            /** Dynamic Conceals */
            dynamic_conceals: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** PracticeSessionCreate */
        PracticeSessionCreate: {
            /** Deck Config Ids */
            deck_config_ids: string[];
        };
        /** PracticeSessionRead */
        PracticeSessionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Curr */
            curr: number;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
        };
        /** SubjectRead */
        SubjectRead: {
            /** Name */
            name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** SubjectUpdate */
        SubjectUpdate: {
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_subject_api_subjects_subject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_subject_api_subjects_subject__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_api_subjects_subject__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_api_subjects_subject__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deck_api_decks_deck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_deck_api_decks_deck__deck_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deck_api_decks_deck__deck_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deck_api_decks_deck__deck_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_card_api_cards_card_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_card_api_cards_card__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_api_cards_card__card_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_api_cards_card__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deck_config_api_deck_configs_deck_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_deck_config_api_deck_configs_deck_config__deck_config_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deck_config_api_deck_configs_deck_config__deck_config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deck_config_api_deck_configs_deck_config__deck_config_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practice_session_api_practice_sessions_practice_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_practice_session_api_practice_sessions_practice_session__practice_session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_practice_card_api_practice_sessions_practice_session__practice_session_id__practice_card_get: {
        parameters: {
            query: {
                forward: boolean;
            };
            header?: never;
            path: {
                practice_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeCardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
