"""subject and deck updated_at and last_activity_at

Revision ID: 053542e7d50b
Revises: 6b878f05fe20
Create Date: 2026-08-22 22:58:19.782209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '053542e7d50b'
down_revision: Union[str, Sequence[str], None] = '6b878f05fe20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """D13: updated_at (audit field) and last_activity_at (recency sort key) for
    subject and deck. `server_default=now()` covers new rows going forward; existing
    rows need an explicit backfill from `created_at` — the plan's own rule (D13:
    "Creation counts as activity") — not from the migration's execution time, which
    `ALTER TABLE ... ADD COLUMN` would otherwise stamp every pre-existing row with,
    making them all tie at "just now" and destroying any real recency signal."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('deck', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subject', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subject', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    op.execute("UPDATE deck SET updated_at = created_at, last_activity_at = created_at")
    op.execute("UPDATE subject SET updated_at = created_at, last_activity_at = created_at")


def downgrade() -> None:
    """Drops both columns outright — nothing else references them yet, so there's no
    data to preserve on the way back down."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'last_activity_at')
    op.drop_column('subject', 'updated_at')
    op.drop_column('deck', 'last_activity_at')
    op.drop_column('deck', 'updated_at')
    # ### end Alembic commands ###
