"""deck-delete cascade: owned rows cascade, review history set null

Revision ID: 222b03167a84
Revises: cde8b1c9da00
Create Date: 2026-08-21 17:38:48.520621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '222b03167a84'
down_revision: Union[str, Sequence[str], None] = 'cde8b1c9da00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Deleting a deck now cascades through its owned, no-independent-life rows
    (field_def, card, deck_practice_config) instead of 500ing on the first leftover
    foreign key. practice_card cascades with its card too — a practice_card without a
    card is meaningless, so it can't exist. review_log is different: it's never
    deleted, so every one of its FKs (card_id, practice_card_id, field_def_id) SETs
    NULL instead — it's the durable historical record that outlives all three.
    practice_deck also SETs NULL on deck_id: it's an immutable session snapshot, not
    deck-owned state, so deleting the source deck must not erase it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_card_deck_id_deck'), 'card', type_='foreignkey')
    op.create_foreign_key(op.f('fk_card_deck_id_deck'), 'card', 'deck', ['deck_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_deck_practice_config_deck_id_deck'), 'deck_practice_config', type_='foreignkey')
    op.create_foreign_key(op.f('fk_deck_practice_config_deck_id_deck'), 'deck_practice_config', 'deck', ['deck_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_field_def_deck_id_deck'), 'field_def', type_='foreignkey')
    op.create_foreign_key(op.f('fk_field_def_deck_id_deck'), 'field_def', 'deck', ['deck_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_practice_card_card_id_card'), 'practice_card', type_='foreignkey')
    op.create_foreign_key(op.f('fk_practice_card_card_id_card'), 'practice_card', 'card', ['card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('practice_deck', 'deck_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_practice_deck_deck_id_deck'), 'practice_deck', type_='foreignkey')
    op.create_foreign_key(op.f('fk_practice_deck_deck_id_deck'), 'practice_deck', 'deck', ['deck_id'], ['id'], ondelete='SET NULL')
    op.alter_column('review_log', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('review_log', 'field_def_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_review_log_card_id_card'), 'review_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_log_practice_card_id_practice_card'), 'review_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_log_field_def_id_field_def'), 'review_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_log_field_def_id_field_def'), 'review_log', 'field_def', ['field_def_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_review_log_card_id_card'), 'review_log', 'card', ['card_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_review_log_practice_card_id_practice_card'), 'review_log', 'practice_card', ['practice_card_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts every column to NOT NULL and every FK to its original no-ondelete form.
    Will fail if any review_log/practice_deck row has actually gone NULL since this
    migration ran (real review or session history pointing at a deleted card/field/
    deck) — that's expected, not a bug: there's no data-preserving way to force a NULL
    back into a NOT NULL column, same as any downgrade that reverts a constraint data
    no longer satisfies."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_review_log_practice_card_id_practice_card'), 'review_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_log_card_id_card'), 'review_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_log_field_def_id_field_def'), 'review_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_log_field_def_id_field_def'), 'review_log', 'field_def', ['field_def_id'], ['id'])
    op.create_foreign_key(op.f('fk_review_log_practice_card_id_practice_card'), 'review_log', 'practice_card', ['practice_card_id'], ['id'])
    op.create_foreign_key(op.f('fk_review_log_card_id_card'), 'review_log', 'card', ['card_id'], ['id'])
    op.alter_column('review_log', 'field_def_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('review_log', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_practice_deck_deck_id_deck'), 'practice_deck', type_='foreignkey')
    op.create_foreign_key(op.f('fk_practice_deck_deck_id_deck'), 'practice_deck', 'deck', ['deck_id'], ['id'])
    op.alter_column('practice_deck', 'deck_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_practice_card_card_id_card'), 'practice_card', type_='foreignkey')
    op.create_foreign_key(op.f('fk_practice_card_card_id_card'), 'practice_card', 'card', ['card_id'], ['id'])
    op.drop_constraint(op.f('fk_field_def_deck_id_deck'), 'field_def', type_='foreignkey')
    op.create_foreign_key(op.f('fk_field_def_deck_id_deck'), 'field_def', 'deck', ['deck_id'], ['id'])
    op.drop_constraint(op.f('fk_deck_practice_config_deck_id_deck'), 'deck_practice_config', type_='foreignkey')
    op.create_foreign_key(op.f('fk_deck_practice_config_deck_id_deck'), 'deck_practice_config', 'deck', ['deck_id'], ['id'])
    op.drop_constraint(op.f('fk_card_deck_id_deck'), 'card', type_='foreignkey')
    op.create_foreign_key(op.f('fk_card_deck_id_deck'), 'card', 'deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###
