"""card_field_mastery behind MasteryStrategy

Revision ID: 25cc44bc1dfe
Revises: 28897c4ca712
Create Date: 2026-08-18 13:38:30.346490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25cc44bc1dfe'
down_revision: Union[str, Sequence[str], None] = '28897c4ca712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_field_mastery',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('field_def_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_mastery', sa.REAL(), nullable=False),
    sa.Column('answer_mastery', sa.REAL(), nullable=False),
    sa.Column('prompt_review_count', sa.Integer(), nullable=False),
    sa.Column('answer_review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_field_mastery_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_def_id'], ['field_def.id'], name=op.f('fk_card_field_mastery_field_def_id_field_def'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'field_def_id', name=op.f('pk_card_field_mastery'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_field_mastery')
    # ### end Alembic commands ###
