"""append-only review_log

Revision ID: 28897c4ca712
Revises: d7c595583b0c
Create Date: 2026-08-18 13:00:11.156207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '28897c4ca712'
down_revision: Union[str, Sequence[str], None] = 'd7c595583b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('practice_card_id', sa.Uuid(), nullable=True),
    sa.Column('field_def_id', sa.Uuid(), nullable=False),
    sa.Column('review_group_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('shown_prompt_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 4', name=op.f('ck_review_log_rating_range')),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_review_log_card_id_card')),
    sa.ForeignKeyConstraint(['field_def_id'], ['field_def.id'], name=op.f('fk_review_log_field_def_id_field_def')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_review_log_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_log')),
    sa.UniqueConstraint('review_group_id', 'field_def_id', name=op.f('uq_review_log_review_group_id'))
    )
    op.create_index('ix_review_log_card_id_field_def_id', 'review_log', ['card_id', 'field_def_id'], unique=False)
    op.create_index('ix_review_log_card_id_reviewed_at', 'review_log', ['card_id', 'reviewed_at'], unique=False)
    op.create_index('ix_review_log_review_group_id', 'review_log', ['review_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_log_review_group_id', table_name='review_log')
    op.drop_index('ix_review_log_card_id_reviewed_at', table_name='review_log')
    op.drop_index('ix_review_log_card_id_field_def_id', table_name='review_log')
    op.drop_table('review_log')
    # ### end Alembic commands ###
