"""initial schema

Revision ID: 49b3d8e1d055
Revises: 
Create Date: 2026-07-27 16:18:58.036725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49b3d8e1d055'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curr', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_session'))
    )
    op.create_table('subject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('name', name=op.f('uq_subject_name'))
    )
    op.create_table('deck',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deck_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_deck_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deck')),
    sa.UniqueConstraint('subject_id', 'name', name=op.f('uq_deck_subject_id'))
    )
    op.create_table('card',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_card_deck_id_deck')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    op.create_table('deck_config',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('static_reveals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('static_conceals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('dynamic_reveals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('dynamic_reveal_quantities', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('dynamic_conceals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('dynamic_conceal_quantities', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('cardinality(dynamic_reveals) = cardinality(dynamic_reveal_quantities)', name=op.f('ck_deck_config_dynamic_reveals_len')),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_deck_config_deck_id_deck')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deck_config'))
    )
    op.create_table('practice_card',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('practice_session_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.BIGINT(), nullable=False),
    sa.Column('static_reveals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('static_conceals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dynamic_reveals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dynamic_conceals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_practice_card_card_id_card')),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], name=op.f('fk_practice_card_practice_session_id_practice_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_card'))
    )
    op.create_index('ix_practice_card_position', 'practice_card', ['practice_session_id', 'position'], unique=False)
    op.create_table('practice_session_deck_config',
    sa.Column('practice_session_id', sa.Uuid(), nullable=False),
    sa.Column('deck_config_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_config_id'], ['deck_config.id'], name=op.f('fk_practice_session_deck_config_deck_config_id_deck_config')),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], name=op.f('fk_practice_session_deck_config_practice_session_id_practice_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_session_deck_config')),
    sa.UniqueConstraint('practice_session_id', 'deck_config_id', name=op.f('uq_practice_session_deck_config_practice_session_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_session_deck_config')
    op.drop_index('ix_practice_card_position', table_name='practice_card')
    op.drop_table('practice_card')
    op.drop_table('deck_config')
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('subject')
    op.drop_table('practice_session')
    # ### end Alembic commands ###
