"""practice_deck source_config_id for attribution-only lineage

Revision ID: 4c84ec429933
Revises: 4b9bd3e5190d
Create Date: 2026-09-10 14:50:44.941624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4c84ec429933'
down_revision: Union[str, Sequence[str], None] = '4b9bd3e5190d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """ADR 040: `practice_deck.source_config_id` (nullable, ON DELETE SET NULL) records
    attribution-only lineage back to the `deck_practice_config` a snapshot was cut
    from — never read by generation, validation, or rerun logic.

    Autogenerate also caught an unrelated drift from the practice_session→practice_run
    rename (task 009 T2): that migration renamed the column but left this table's own
    unique constraint under its pre-rename name
    (`uq_practice_deck_practice_session_id`), out of step with what the current model's
    naming convention now derives from the renamed column
    (`uq_practice_deck_practice_run_id`). Folded in here since it's a same-table,
    no-behavior-change rename and this migration was already touching the table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_deck', sa.Column('source_config_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_practice_deck_practice_session_id'), 'practice_deck', type_='unique')
    op.create_unique_constraint(op.f('uq_practice_deck_practice_run_id'), 'practice_deck', ['practice_run_id', 'deck_id'])
    op.create_foreign_key(op.f('fk_practice_deck_source_config_id_deck_practice_config'), 'practice_deck', 'deck_practice_config', ['source_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops the column and reverts the unique constraint to its pre-rename name."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_practice_deck_source_config_id_deck_practice_config'), 'practice_deck', type_='foreignkey')
    op.drop_constraint(op.f('uq_practice_deck_practice_run_id'), 'practice_deck', type_='unique')
    op.create_unique_constraint(op.f('uq_practice_deck_practice_session_id'), 'practice_deck', ['practice_run_id', 'deck_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('practice_deck', 'source_config_id')
    # ### end Alembic commands ###
