"""deck subject cascade on delete

Revision ID: 6b878f05fe20
Revises: 4d6f127ae6a6
Create Date: 2026-08-22 16:55:49.259046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6b878f05fe20'
down_revision: Union[str, Sequence[str], None] = '4d6f127ae6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """D12 covered every deck-owned row cascading from a deck delete, but never stated
    what happens to a deck when its *subject* is deleted — deck.subject_id had no
    ondelete at all, so DELETE /api/subjects/{id} 500'd (ForeignKeyViolation) the
    moment the subject had any deck, exactly like the deck-delete gap this mirrors.
    Subject delete cascades through its decks (and everything the deck-delete cascade
    already cascades from there), matching what SubjectForm's delete confirm has
    always told the user would happen (§4.2, §6)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_deck_subject_id_subject'), 'deck', type_='foreignkey')
    op.create_foreign_key(op.f('fk_deck_subject_id_subject'), 'deck', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts to no ondelete (RESTRICT) on deck.subject_id."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_deck_subject_id_subject'), 'deck', type_='foreignkey')
    op.create_foreign_key(op.f('fk_deck_subject_id_subject'), 'deck', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###
