"""app_user timezone for user-local date rendering

Revision ID: 8b87efa6aa86
Revises: d99d2883e31f
Create Date: 2026-08-24 13:33:58.782968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8b87efa6aa86'
down_revision: Union[str, Sequence[str], None] = 'd99d2883e31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'timezone')
    # ### end Alembic commands ###
