"""practice_deck source_config_name

Revision ID: 9de2fd4c3f06
Revises: f6887865090a
Create Date: 2026-10-01 21:15:00.233848

ADR 066 (task 022 T1): practice_deck gains a nullable source_config_name, the name of
the configuration a snapshot was cut from as of the last moment its source_config_id
link existed. The practice summary falls back to it for a deck's configuration label
once the link is gone.

Upgrade, in order:
1. Add the nullable practice_deck.source_config_name column.
2. Backfill it on every snapshot whose source_config_id still resolves, from the linked
   configuration's current name. A linked configuration's layout cannot have changed
   since the snapshot (ADR 040's sever rule), only its name, so this is the value ADR
   066's rules would have maintained. Snapshots with a null link stay null; there is
   nothing to copy from.

Downgrade drops the column, which removes the backfill with it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9de2fd4c3f06'
down_revision: Union[str, Sequence[str], None] = 'f6887865090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_deck', sa.Column('source_config_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE practice_deck
        SET source_config_name = deck_practice_config.name
        FROM deck_practice_config
        WHERE deck_practice_config.id = practice_deck.source_config_id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_deck', 'source_config_name')
    # ### end Alembic commands ###
