"""field_def, card, card_field_value with archival semantics

Revision ID: d7c595583b0c
Revises: 
Create Date: 2026-08-18 12:15:55.021405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd7c595583b0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('clerk_user_id', name=op.f('uq_app_user_clerk_user_id'))
    )
    op.create_table('subject',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_subject_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('user_id', 'name', name=op.f('uq_subject_user_id'))
    )
    op.create_table('deck',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_deck_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deck')),
    sa.UniqueConstraint('subject_id', 'name', name=op.f('uq_deck_subject_id'))
    )
    op.create_table('card',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_card_deck_id_deck')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    op.create_table('field_def',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('text', 'image', 'audio')", name=op.f('ck_field_def_type_valid')),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_field_def_deck_id_deck')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_def')),
    sa.UniqueConstraint('deck_id', 'position', deferrable=True, initially='DEFERRED', name=op.f('uq_field_def_deck_id'))
    )
    op.create_index('uq_field_def_deck_id_name_active', 'field_def', ['deck_id', 'name'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('card_field_value',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('field_def_id', sa.Uuid(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_field_value_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_def_id'], ['field_def.id'], name=op.f('fk_card_field_value_field_def_id_field_def'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'field_def_id', name=op.f('pk_card_field_value'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_field_value')
    op.drop_index('uq_field_def_deck_id_name_active', table_name='field_def', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('field_def')
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('subject')
    op.drop_table('app_user')
    # ### end Alembic commands ###
