"""practice config tables and validation

Revision ID: e52792c2937f
Revises: 25cc44bc1dfe
Create Date: 2026-08-18 17:20:23.312962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e52792c2937f'
down_revision: Union[str, Sequence[str], None] = '25cc44bc1dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_session',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name=op.f('ck_practice_session_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_practice_session_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_session'))
    )
    op.create_table('deck_practice_config',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_field_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('answer_field_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('prompt_pool_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('prompt_pool_counts', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('answer_pool_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('answer_pool_counts', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_deck_practice_config_deck_id_deck')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deck_practice_config')),
    sa.UniqueConstraint('deck_id', 'name', name=op.f('uq_deck_practice_config_deck_id'))
    )
    op.create_table('practice_deck',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_session_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_field_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('answer_field_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('prompt_pool_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('prompt_pool_counts', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('answer_pool_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('answer_pool_counts', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_practice_deck_deck_id_deck')),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], name=op.f('fk_practice_deck_practice_session_id_practice_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_deck')),
    sa.UniqueConstraint('practice_session_id', 'deck_id', name=op.f('uq_practice_deck_practice_session_id'))
    )
    op.create_table('practice_card',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_session_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=False),
    sa.Column('prompts', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('answers', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'passed', 'failed')", name=op.f('ck_practice_card_status_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_practice_card_card_id_card')),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], name=op.f('fk_practice_card_practice_session_id_practice_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_card')),
    sa.UniqueConstraint('practice_session_id', 'position', name=op.f('uq_practice_card_practice_session_id'))
    )
    op.create_index('ix_practice_card_session_status_position', 'practice_card', ['practice_session_id', 'status', 'position'], unique=False)
    op.create_foreign_key(op.f('fk_review_log_practice_card_id_practice_card'), 'review_log', 'practice_card', ['practice_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_review_log_practice_card_id_practice_card'), 'review_log', type_='foreignkey')
    op.drop_index('ix_practice_card_session_status_position', table_name='practice_card')
    op.drop_table('practice_card')
    op.drop_table('practice_deck')
    op.drop_table('deck_practice_config')
    op.drop_table('practice_session')
    # ### end Alembic commands ###
