"""rename practice card field names

Revision ID: e945ee018a0e
Revises: ff193c590ce3
Create Date: 2026-08-10 19:14:04.953957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e945ee018a0e'
down_revision: Union[str, Sequence[str], None] = 'ff193c590ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_card', sa.Column('prompt_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('practice_card', sa.Column('answer_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('practice_card', sa.Column('prompt_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('practice_card', sa.Column('answer_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('practice_card', 'dynamic_reveals')
    op.drop_column('practice_card', 'static_reveals')
    op.drop_column('practice_card', 'static_conceals')
    op.drop_column('practice_card', 'dynamic_conceals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_card', sa.Column('dynamic_conceals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('practice_card', sa.Column('static_conceals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('practice_card', sa.Column('static_reveals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('practice_card', sa.Column('dynamic_reveals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('practice_card', 'answer_pool')
    op.drop_column('practice_card', 'prompt_pool')
    op.drop_column('practice_card', 'answer_fields')
    op.drop_column('practice_card', 'prompt_fields')
    # ### end Alembic commands ###
